[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]

[phases.install]
cmds = ["pnpm i --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "cd artifacts/berapanel && pnpm run serve"
